spring:
  application:
    name: ad-eureka

server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
      allow-redirects: false
      fetch-registry: false
      register-with-eureka: false
      service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



